/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:df8117f5-90b3-45c0-b23e-67e743c3b777",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_K3VLs6DkN",
    "aws_user_pools_web_client_id": "6epp6kk5atd5n3vohfg3dntavd",
    "oauth": {}
};


export default awsmobile;
